"use client";

import { Canvas, useFrame, useLoader, useThree } from "@react-three/fiber";
import {
  Suspense,
  useEffect,
  useMemo,
  useRef,
  MutableRefObject,
} from "react";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";

/**
 * The ring models are parametric CAD, generated by
 * scripts/generate_rings.py (trimesh: swept superellipse band profiles,
 * cathedral shoulders, parallel-transport claw sweeps, convex-hull
 * brilliant cuts) and exported to public/models/*.glb. This component
 * loads them and dresses the named meshes in studio materials.
 */

interface SpinState {
  vx: number;
  vy: number;
  dragging: boolean;
  idle: number;
}

const rand = (min: number, max: number) => min + Math.random() * (max - min);

/* ── Studio environment, baked twice ──────────────────────────────────────
   Soft blur for creamy platinum reflections; razor-sharp for stone
   facet flashes. Assigned per material. */
function buildStudio(): THREE.Scene {
  const env = new THREE.Scene();
  const panel = (intensity: number) => {
    const mat = new THREE.MeshBasicMaterial();
    mat.color.setScalar(intensity);
    return mat;
  };

  const R = 9;
  const COUNT = 16;
  for (let i = 0; i < COUNT; i++) {
    const a = (i / COUNT) * Math.PI * 2;
    const intensity =
      i % 2 === 0 ? (i % 4 === 0 ? 9 : 4.5) : i % 3 === 0 ? 0.4 : 0.08;
    const m = new THREE.Mesh(new THREE.PlaneGeometry(2.2, 8), panel(intensity));
    m.position.set(Math.sin(a) * R, 0, Math.cos(a) * R);
    m.rotation.y = a + Math.PI;
    env.add(m);
  }
  const top = new THREE.Mesh(new THREE.PlaneGeometry(10, 10), panel(6.5));
  top.position.set(0, 8, 0);
  top.rotation.x = Math.PI / 2;
  env.add(top);
  const floor = new THREE.Mesh(new THREE.PlaneGeometry(12, 12), panel(0.7));
  floor.position.set(0, -8, 0);
  floor.rotation.x = -Math.PI / 2;
  env.add(floor);
  return env;
}

interface StudioMats {
  polished: THREE.MeshPhysicalMaterial;
  satin: THREE.MeshPhysicalMaterial;
  pave: THREE.MeshPhysicalMaterial;
  gem: THREE.MeshPhysicalMaterial;
}

function useStudio(): StudioMats {
  const { gl, scene } = useThree();

  const { sharp, soft, mats } = useMemo(() => {
    const pmrem = new THREE.PMREMGenerator(gl);
    const studioA = buildStudio();
    const sharp = pmrem.fromScene(studioA, 0.005).texture;
    const studioB = buildStudio();
    const soft = pmrem.fromScene(studioB, 0.6).texture;
    pmrem.dispose();
    [studioA, studioB].forEach((s) =>
      s.traverse((o) => {
        if (o instanceof THREE.Mesh) {
          o.geometry.dispose();
          (o.material as THREE.Material).dispose();
        }
      })
    );

    const polished = new THREE.MeshPhysicalMaterial({
      color: 0xf4f3f1,
      metalness: 1,
      roughness: 0.12,
      clearcoat: 0.5,
      clearcoatRoughness: 0.15,
      envMap: soft,
      envMapIntensity: 1.5,
    });
    const satin = new THREE.MeshPhysicalMaterial({
      color: 0xeceae7,
      metalness: 1,
      roughness: 0.28,
      envMap: soft,
      envMapIntensity: 1.3,
    });
    const pave = new THREE.MeshPhysicalMaterial({
      color: 0xffffff,
      metalness: 0,
      roughness: 0.02,
      clearcoat: 1,
      clearcoatRoughness: 0,
      envMap: sharp,
      envMapIntensity: 3.6,
      specularIntensity: 1.3,
    });
    const gem = new THREE.MeshPhysicalMaterial({
      color: 0xffffff,
      metalness: 0,
      roughness: 0,
      transmission: 1,
      thickness: 2.2,
      ior: 2.42,
      dispersion: 4.5,
      clearcoat: 1,
      clearcoatRoughness: 0,
      specularIntensity: 1,
      envMap: sharp,
      envMapIntensity: 3.2,
      side: THREE.DoubleSide,
    });

    return { sharp, soft, mats: { polished, satin, pave, gem } };
  }, [gl]);

  useEffect(() => {
    scene.environment = sharp;
    return () => {
      scene.environment = null;
      sharp.dispose();
      soft.dispose();
      Object.values(mats).forEach((m) => m.dispose());
    };
  }, [scene, sharp, soft, mats]);

  return mats;
}

/* ── CAD model loader — dresses named meshes in studio materials ───────── */
function RingModel({
  url,
  mats,
  metal,
}: {
  url: string;
  mats: StudioMats;
  metal: "polished" | "satin";
}) {
  const gltf = useLoader(GLTFLoader, url);

  const object = useMemo(() => {
    const root = gltf.scene.clone(true);
    root.traverse((o) => {
      const mesh = o as THREE.Mesh;
      if (!mesh.isMesh) return;
      const n = (mesh.name || "").toLowerCase();
      if (n.includes("gem")) mesh.material = mats.gem;
      else if (n.includes("pave")) mesh.material = mats.pave;
      else mesh.material = metal === "satin" ? mats.satin : mats.polished;
    });
    return root;
  }, [gltf, mats, metal]);

  return <primitive object={object} />;
}

/* ── Camera-glint texture for scintillation sprites ───────────────────── */
function makeGlintTexture(): THREE.Texture {
  const size = 64;
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext("2d")!;
  const c = size / 2;
  ctx.globalCompositeOperation = "lighter";

  const core = ctx.createRadialGradient(c, c, 0, c, c, 9);
  core.addColorStop(0, "rgba(255,255,255,1)");
  core.addColorStop(1, "rgba(255,255,255,0)");
  ctx.fillStyle = core;
  ctx.fillRect(0, 0, size, size);

  const ray = (angle: number, len: number) => {
    ctx.save();
    ctx.translate(c, c);
    ctx.rotate(angle);
    const g = ctx.createLinearGradient(-len, 0, len, 0);
    g.addColorStop(0, "rgba(255,255,255,0)");
    g.addColorStop(0.5, "rgba(255,255,255,0.95)");
    g.addColorStop(1, "rgba(255,255,255,0)");
    ctx.fillStyle = g;
    ctx.fillRect(-len, -1.2, len * 2, 2.4);
    ctx.restore();
  };
  ray(0, 30);
  ray(Math.PI / 2, 30);

  return new THREE.CanvasTexture(canvas);
}

/** Twinkling glints riding the center stone. */
function GemSparkles() {
  const tex = useMemo(makeGlintTexture, []);
  const data = useMemo(
    () =>
      Array.from({ length: 13 }, () => ({
        pos: [rand(-0.16, 0.16), 1.5 + rand(-0.06, 0.12), rand(-0.38, 0.38)] as [
          number,
          number,
          number
        ],
        speed: rand(1.6, 3.8),
        phase: rand(0, Math.PI * 2),
        size: rand(0.09, 0.2),
      })),
    []
  );
  const refs = useRef<(THREE.Sprite | null)[]>([]);

  useFrame(({ clock }) => {
    const t = clock.elapsedTime;
    data.forEach((s, i) => {
      const sp = refs.current[i];
      if (!sp) return;
      const k = Math.max(0, Math.sin(t * s.speed + s.phase));
      const v = Math.pow(k, 8);
      sp.scale.setScalar(s.size * (0.3 + v));
      (sp.material as THREE.SpriteMaterial).opacity = v;
    });
  });

  return (
    <>
      {data.map((s, i) => (
        <sprite
          key={i}
          ref={(el) => {
            refs.current[i] = el;
          }}
          position={s.pos}
        >
          <spriteMaterial
            map={tex}
            transparent
            opacity={0}
            depthWrite={false}
            blending={THREE.AdditiveBlending}
          />
        </sprite>
      ))}
    </>
  );
}

/* ── The rings — CAD models in interlocked arrangement ─────────────────── */
function Rings({ spin }: { spin: MutableRefObject<SpinState> }) {
  const group = useRef<THREE.Group>(null);
  const mats = useStudio();

  useFrame(() => {
    const g = group.current;
    if (!g) return;
    const s = spin.current;
    g.rotation.y += s.vx;
    g.rotation.x += s.vy;
    if (!s.dragging) {
      s.vx += (s.idle - s.vx) * 0.03;
      s.vy += (0 - s.vy) * 0.03;
    }
  });

  return (
    <group ref={group} position={[0, -0.12, 0]} rotation={[0.35, -0.6, 0.08]}>
      {/* His wedding band — satin */}
      <group position={[-0.45, 0, 0]} rotation={[0, 0, Math.PI / 2]}>
        <RingModel url="/models/wedding_band.glb" mats={mats} metal="satin" />
      </group>

      {/* Her engagement ring — polished, threaded through his */}
      <group position={[0.45, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <RingModel url="/models/engagement.glb" mats={mats} metal="polished" />
        <GemSparkles />
      </group>
    </group>
  );
}

export default function Rings3D() {
  const spin = useRef<SpinState>({ vx: 0.006, vy: 0, dragging: false, idle: 0.006 });
  const last = useRef({ x: 0, y: 0 });

  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      spin.current.idle = 0;
      spin.current.vx = 0;
    }
  }, []);

  return (
    <div
      className="h-[380px] md:h-[480px] cursor-grab active:cursor-grabbing"
      // pan-y keeps vertical page scrolling alive on touch — horizontal
      // drags spin the rings
      style={{ touchAction: "pan-y" }}
      onPointerDown={(e) => {
        spin.current.dragging = true;
        last.current = { x: e.clientX, y: e.clientY };
        e.currentTarget.setPointerCapture(e.pointerId);
      }}
      onPointerMove={(e) => {
        if (!spin.current.dragging) return;
        const dx = e.clientX - last.current.x;
        const dy = e.clientY - last.current.y;
        last.current = { x: e.clientX, y: e.clientY };
        spin.current.vx = dx * 0.0035;
        spin.current.vy = dy * 0.002;
      }}
      onPointerUp={(e) => {
        spin.current.dragging = false;
        e.currentTarget.releasePointerCapture(e.pointerId);
      }}
      onPointerCancel={() => {
        spin.current.dragging = false;
      }}
    >
      <Canvas
        camera={{ position: [0, 0, 5.9], fov: 45 }}
        gl={{ alpha: true, antialias: true }}
        dpr={[1, 2]}
        onCreated={({ gl }) => {
          gl.toneMappingExposure = 1.15;
        }}
      >
        <ambientLight intensity={0.3} />
        <directionalLight position={[5, 6, 4]} intensity={1.2} />
        <pointLight position={[-5, -2, 4]} intensity={0.45} color="#fff1e0" />
        <Suspense fallback={null}>
          <Rings spin={spin} />
        </Suspense>
      </Canvas>
    </div>
  );
}
